### ISSUE TITLE
未实现项目清单 / List of unimplemented things

### ISSUE THREAD

**Issue by zeng-github01** [AE2-UEL/MekanismEnergistics#1]
- [ ] ME气体存储监控器 / ME Gas Storage Monitor
- [ ] ME气体交换监控器 / ME Gas Conversion Monitor

**Comment by zeng-github01** [comment]
@GlodBlock 等你这边弄好了之后，我打算改一下AEAddition 那边，让它用你这个Mod 的组件，AEA那边写的太放飞自我了。改完之后打算自用

气体总线需要先设置储罐为输出才能用，这是有意设置的嘛？还是说配合MEK的限制，AEA貌似没有这个要求

**Comment by GlodBlock** [comment]
那肯定是储罐设置输出才能抽阿

**Comment by GlodBlock** [comment]
气体终端不是有了吗，你说的气体终端交互是什么

**Comment by zeng-github01** [comment]
> 气体终端不是有了吗，你说的气体终端交互是什么

GUI里面拿罐子，不能存取气体。所谓的交互就是这个意思

正常像流体终端的话拿桶，存取流体。那个还行。但是这个的话。储罐是完全没有反应的

**Comment by zeng-github01** [comment]
> 那肯定是储罐设置输出才能抽阿

隔壁AEA放上去就可以抽了，侧边是输入都行。要不作者再改进一下？

**Comment by GlodBlock** [comment]
不是能的吗

**Comment by GlodBlock** [comment]
和流体终端一样

**Comment by zeng-github01** [comment]
> 不是能的吗

我把AEA删了试一下。我这不行

**Comment by GlodBlock** [comment]
![1](https://github.com/AE2-UEL/MekanismEnergistics/assets/60341015/6602bb5f-38b4-4358-b319-952ffa4812f5)

**Comment by zeng-github01** [comment]
> ![1](https://private-user-images.githubusercontent.com/60341015/335554156-6602bb5f-38b4-4358-b319-952ffa4812f5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTM4NTksIm5iZiI6MTcxNzE1MzU1OSwicGF0aCI6Ii82MDM0MTAxNS8zMzU1NTQxNTYtNjYwMmJiNWYtMzhiNC00MzU4LWIzMTktOTUyZmZhNDgxMmY1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDExMDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllOTU5ZDNjNDE2YzY3ZmQ2NzliOTczZmE4YWY0ZmE3NWE1ZThhNTBkMTA4MWNmNWMwNTk1NTYwYzNkMDYwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0pXHiqmYM0SeRGPSjpTUlWev1YJ1x1LzTW_bsgm0isA) [ ![1](https://private-user-images.githubusercontent.com/60341015/335554156-6602bb5f-38b4-4358-b319-952ffa4812f5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTM4NTksIm5iZiI6MTcxNzE1MzU1OSwicGF0aCI6Ii82MDM0MTAxNS8zMzU1NTQxNTYtNjYwMmJiNWYtMzhiNC00MzU4LWIzMTktOTUyZmZhNDgxMmY1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDExMDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllOTU5ZDNjNDE2YzY3ZmQ2NzliOTczZmE4YWY0ZmE3NWE1ZThhNTBkMTA4MWNmNWMwNTk1NTYwYzNkMDYwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0pXHiqmYM0SeRGPSjpTUlWev1YJ1x1LzTW_bsgm0isA) ](https://private-user-images.githubusercontent.com/60341015/335554156-6602bb5f-38b4-4358-b319-952ffa4812f5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTM4NTksIm5iZiI6MTcxNzE1MzU1OSwicGF0aCI6Ii82MDM0MTAxNS8zMzU1NTQxNTYtNjYwMmJiNWYtMzhiNC00MzU4LWIzMTktOTUyZmZhNDgxMmY1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDExMDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllOTU5ZDNjNDE2YzY3ZmQ2NzliOTczZmE4YWY0ZmE3NWE1ZThhNTBkMTA4MWNmNWMwNTk1NTYwYzNkMDYwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0pXHiqmYM0SeRGPSjpTUlWev1YJ1x1LzTW_bsgm0isA) [ ](https://private-user-images.githubusercontent.com/60341015/335554156-6602bb5f-38b4-4358-b319-952ffa4812f5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTM4NTksIm5iZiI6MTcxNzE1MzU1OSwicGF0aCI6Ii82MDM0MTAxNS8zMzU1NTQxNTYtNjYwMmJiNWYtMzhiNC00MzU4LWIzMTktOTUyZmZhNDgxMmY1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDExMDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllOTU5ZDNjNDE2YzY3ZmQ2NzliOTczZmE4YWY0ZmE3NWE1ZThhNTBkMTA4MWNmNWMwNTk1NTYwYzNkMDYwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0pXHiqmYM0SeRGPSjpTUlWev1YJ1x1LzTW_bsgm0isA)

靠，我用的CE的分支，这个分支在逐步向MEK V10 更新，是不是有点兼容性问题？作者你要不看看

**Comment by zeng-github01** [comment]
仓库在这：https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2

虽然我个人感觉其实他也没做什么对储罐的修改

用这个分支这么久了，这是唯一一次不兼容，隔壁的AEA都没问题

**Comment by GlodBlock** [comment]
有改过，那个作者和我提过
但是我没法同时兼容两个分支

**Comment by zeng-github01** [comment]
> 有改过，那个作者和我提过 但是我没法同时兼容两个分支

他改了什么？能稍微说一下嘛？用户侧完全无感啊？而且为啥隔壁AEA没问题

**Comment by GlodBlock** [comment]
BaseTier换位置了

**Comment by GlodBlock** [comment]
你能不能进cleanroom的dc聊，大部分人都在那里 https://discord.gg/f2K4aSpG4F

**Comment by zeng-github01** [comment]
> BaseTier换位置了

只是换了包路径嘛？可以考虑一下Class.forName吧？ 这下尴尬了


DC的话，我到目前都是没号....

**Comment by asdflj** [comment]
![3de78a5819515b11bba10d7a3e360fcf](https://github.com/AE2-UEL/MekanismEnergistics/assets/33802162/6c7a432f-1382-4c11-ad76-ee52dd7fb81c)

**Comment by GlodBlock** [comment]
很麻烦，它方法签名都要改，dc你用qq邮箱都能注册，github上聊不方便

**Comment by zeng-github01** [comment]
> 很麻烦，它方法签名都要改，dc你用qq邮箱都能注册，github上聊不方便

我有一个用邮箱的，但是它强制要我手机号，考虑到这玩意是个被墙的软件。我不太敢用手机注册

**Comment by asdflj** [comment]
![image](https://github.com/AE2-UEL/MekanismEnergistics/assets/33802162/05741a1b-a9b7-4bbb-aadc-c6197e5568ee)
@GlodBlock

**Comment by zeng-github01** [comment]
> ![image](https://private-user-images.githubusercontent.com/33802162/335557521-05741a1b-a9b7-4bbb-aadc-c6197e5568ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTQ2NjQsIm5iZiI6MTcxNzE1NDM2NCwicGF0aCI6Ii8zMzgwMjE2Mi8zMzU1NTc1MjEtMDU3NDFhMWItYTliNy00YmJiLWFhZGMtYzYxOTdlNTU2OGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDExMTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNmYzOTNhNzIzNzRjNTNhNzM0YmEwMzYwMjFmYmIyYTg5ZjBiNTQzZjEwZDAzOTI5Y2MwMTViMDBhYTlhMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LlH5qQeMTyG8x61RmuVX9QXrAc0G9AFXr6TFck_kDLg) @GlodBlock

小场面，不影响编译。我试过了

**Comment by asdflj** [comment]
依赖无法下载哦

**Comment by zeng-github01** [comment]
> 很麻烦，它方法签名都要改，dc你用qq邮箱都能注册，github上聊不方便

卧槽，那AEA是用什么黑科技兼容的。我确定我没改过这。虽然它是要放到GUI的一个槽里就是了

**Comment by zeng-github01** [comment]
> 依赖无法下载哦

这个我遇到过，图都和你一样，你直接编译就是了，这个是个伪报错。当然前提是你的网络没问题

**Comment by asdflj** [comment]
我都无法运行

**Comment by asdflj** [comment]
![image](https://github.com/AE2-UEL/MekanismEnergistics/assets/33802162/33351106-c0a5-4a72-954d-f16c81658880)

**Comment by zeng-github01** [comment]
> 我都无法运行

那就不清楚了，克隆的第一次同步的结果都这样。我是直接编译的，因为我对我自己的网有信心。事实上也没问题

实在不行你就build 一下，之后重新sync一下就行了

**Comment by asdflj** [comment]
大佬,可以了

**Comment by asdflj** [comment]
这个气体接口怎么用
@GlodBlock

**Comment by asdflj** [comment]
是不是要气体样板终端啊

**Comment by zeng-github01** [comment]
> 是不是要气体样板终端啊

和流体接口是一样的啊。就是用来接收气体的

**Comment by asdflj** [comment]
接收气体,用气体输入总线不就好了

**Comment by zeng-github01** [comment]
> 接收气体,用气体输入总线不就好了

这玩意本质上就是个容器。和总线不一样的。总线只能用在一个设备上。接口可以接加压管道串联

**Comment by GlodBlock** [comment]
我刚刚用ceu分支的mek试过了，能正常在气体终端上交互的

**Comment by zeng-github01** [comment]
> 我刚刚用ceu分支的mek试过了，能正常在气体终端上交互的

那我再试试，因为我这个是个测试专用的端，可能是忘记更新构建了，马上去试试看

**Comment by GlodBlock** [comment]
你的mek版本是多少

**Comment by zeng-github01** [comment]
> 你的mek版本是多少

确认了，最新的action 构建，日志的报错和你说的一致：Caused by: java.lang.NoSuchMethodError: mekanism.common.base.ITierItem.getBaseTier(Lnet/minecraft/item/ItemStack;)Lmekanism/common/tier/BaseTier;

**Comment by zeng-github01** [comment]
@GlodBlock 经过测试，发现存储监视器自带流体的支持，也就是说不需要单独的监视器支持。只需要集成到AE2的监视器上就行

话说作者大大能不能给AE2的那个交换监视器打个补丁PR修改一下它的逻辑。目前现有的逻辑不符合下意识认知。
如果手上的空桶大于1 ，就不能从交换监视器打到水。能不能把它修改成一桶一桶打。和流体终端的逻辑一致，但是不一次性打完

**Comment by zeng-github01** [comment]
@GlodBlock 看了一下AE原生的监视器支持，它是直接把物品和流体堆栈写进去的，那这个情况，应该不太好操作了。包括一些渲染也是写死的。除非是全部改为IAEStack. 目前我使用原生的流体逻辑改写了一个气体逻辑的监视器。功能完整。除了物品栏里面还没绑定材质。模型用的AE2自带监视器。要不先提交一个PR？然后作者你再改改

修改1：突然想起来还没加合成表

**Comment by asdflj** [comment]
gkd

**Comment by zeng-github01** [comment]
> gkd

本来想给AE2的那个监控器加上气体逻辑。但是加上之后有Bug 真操蛋

**Comment by asdflj** [comment]
> > gkd
> 
> 本来想给AE2的那个监控器加上气体逻辑。但是加上之后有Bug 真操蛋

@GlodBlock

**Comment by zeng-github01** [comment]
> > > gkd
> > 
> > 
> > 本来想给AE2的那个监控器加上气体逻辑。但是加上之后有Bug 真操蛋
> 
> @GlodBlock

目前完成了一半，把气体储罐的加上去了，把物品和流体的搞炸了。还得debug

**Comment by zeng-github01** [comment]
@asdflj AE2那边的集成是没办法了。这边加了一个半成品，看作者要不要了

**Comment by asdflj** [comment]
发pr啊,让我康康
