### ISSUE TITLE
与mekceu崩溃

### ISSUE THREAD

**Issue by sddsd2332** [AE2-UEL/MekanismEnergistics#2]
日志：https://mclo.gs/vBLdeCI
mek版本：https://www.curseforge.com/minecraft/mc-mods/mekanism-ce-unofficial/files/5392927
MekanismEnergistics版本：https://www.curseforge.com/minecraft/mc-mods/mekanism-energistics/files/5389347

**Comment by GlodBlock** [comment]
修了
