### ISSUE TITLE
[Request] 对AEA版本的气体磁盘添加迁移支持

### ISSUE THREAD

**Issue by zeng-github01** [AE2-UEL/MekanismEnergistics#3]
对AEAddition的气体磁盘添加基本的迁移支持，使得它可以通过IO端口迁移至该Mod的磁盘中

不过我觉得还是研究一下，怎么把AEA磁盘的存储频道改到这个Mod的频道更好

**Comment by GlodBlock** [comment]
不是很想做ec的支持，因为这个mod本来就是代替ec的气体组件的

**Comment by zeng-github01** [comment]
> 不是很想做ec的支持，因为这个mod本来就是代替ec的气体组件的

我自己在尝试把EC的存储通道改成这里的。就不用EC那些垃圾玩意了。但是莫名其妙的有Bug崩了 怎么看都看不出问题

明明是气体通道，流体的盘反倒崩了。气死了。作者能帮忙看看吗？我在我仓库开个迁移分支

https://github.com/zeng-github01/AE-Additions-1.12.2-AE2-Extend-Life/tree/gas

**Comment by zeng-github01** [comment]
还有就是，气体磁盘的可存储种类建议改为5种，和流体盘一致

@GlodBlock 

打算给NAE那边加上更大的存储磁盘吗？

**Comment by zeng-github01** [comment]
AEA侧的迁移搞定了，就等作者你搞气体二合一接口了 @GlodBlock 

还有就是距离彻底淘汰AEA的话，还需要一些东西的移植。这个我开了个Issue 在隔壁NAE
