### ISSUE TITLE
Transfer factor question

### ISSUE THREAD

**Issue by NotMyWing** [AE2-UEL/MekanismEnergistics#6]
Hey there!

https://github.com/AE2-UEL/MekanismEnergistics/blob/9967e4b767f977f3f388803b6d48effd62a83fec/src/main/java/com/mekeng/github/common/me/storage/impl/GasStorageChannel.java#L27-L29

I'm using this value to display user-friendly units in NAE2's Cell View. For items and fluids it's 1 and 1000 respectively, corresponding to 1 item and 1000mB:1B. Why is 4000 used here?

**Comment by GlodBlock** [comment]
in mek v10, the fluid pipe transfer rate is 250mb/t and gas pipe transfer rate is 1000mb/t, so i choose 4000 which is 4 times more than fluid transfer rate
